### ISSUE TITLE
Smartd service won't start - release 6.6.1

### ISSUE THREAD

**Issue by dhatch48** [deajan/smartmontools-win#24] opened 2018-06-15 18:14 UTC
Thank you for this project. I wanted to let you know that there is an issue with smartd.exe in the 6.6.1 release.

I just tried installing this fresh on a windows 7 x64 pc and could not get the smartd service to run.
Here is the message from eventlog:

> smartd[2436]:CRIT
>  File C:\Program Files\smartmontools for Windows\bin\smartd.conf line 3 (drive DEVICESCAN): unknown Directive: Files\smartmontools
>  Run smartd -D to print a list of valid Directives.
>  Configuration file C:\Program Files\smartmontools for Windows\bin\smartd.conf has fatal syntax errors.

Once I saw this I also tried editing the conf file and replacing DEVICESCAN with /dev/sda but this still did not work.

The contents of the config was default except for changing the scheduled time for tests

**Comment by deajan** [comment] 2018-06-15 20:52
Thanks for the report, but this is a duplicate of #23

**Closed** 2019-04-26 20:51 UTC
